# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56415d75d3d5fb6b385ab5b09cbf555f63632593090442f2bf4beaf78bdb1f664769dd9c70191af2043abb3b3acbbf59a397aea849f69d0ad0950914fc66b464

test:
  secret_key_base: c40da06bca51e758cdf1c38984dae9255eda51a3359d40b5336ba43475948280f1799a40f955429ddd51db903a294411f42c2ce75e557f2792ad7c99927ce936

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
